language: python
python:
  - "3.6"
sudo: false
dist: trusty

notifications:
    emails:
        - technext.jpn@gmail.com
    on_success: always
    on_failure: always

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda env create -f environment.yml;
  - source activate arxiv-bot;
  - pip install -e .

script:
  - pwd
  - pip install flake8
  - pip install hacking
  - pip install autopep8
  - pip install mock
  - pip install pytest
  - pip install pytest-cov
  - make test
  - py.test --cov=./arxiv-bot --cov-config .coveragerc

after_success:
  - codecov -t d03d5756-3cfe-4cfb-b54c-87449deb733c
